accounts/urls.py
from django import views
from django.urls import path
from .views import index, register,login, logout
app_name = 'accounts'

urlpatterns = [
    path('',index, name="home"),
    # path('###',save_reg,name="save"),
    path('register',register, name="register"),
    path('login',login, name="login"),
    path('logout',logout, name="logout"),
]

cs50finance/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')), 
    path('dashboard/', include('dashboard.urls')), 
]

dashboard/urls.py
from django.urls import path
from .views import portfolio, buy, sell, history, quotes

app_name = 'dashboard'
urlpatterns = [
    path('', portfolio,name='index'),
    path('buy', buy,name='buy'),
    path('sell', sell,name='sell'),
    path('history', history,name='history'),
    path('quotes', quotes,name='quotes'),
]

dashboard/models.py
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()
# Create your models here.
class Stock(models.Model):
    name = models.CharField(max_length=100)
    symbol = models.CharField(max_length=31)
    price = models.DecimalField( decimal_places=2, max_digits=8)
    website = models.URLField()
    sector = models.CharField(max_length=100)
    industry = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    logo_url = models.URLField()
    updated = models.DateTimeField()
    users = models.ManyToManyField(User,related_name='bought_stocks')

    def __str__(self):
        return f'{self.symbol} -> {self.updated.ctime()}'
    class Meta:
        ordering = ['-updated']

class BoughtStockTrack(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE, related_name='bought_stock_tracks')
    symbol = models.CharField(max_length=31)
    shares = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f'{self.user.username} -> {self.symbol} -> {self.shares}'

class Transaction(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE, related_name='transactions')
    stock_name = models.CharField(max_length=100)
    stock_symbol = models.CharField(max_length=31)
    stock_price = models.DecimalField(decimal_places=2, max_digits=10)
    shares = models.PositiveIntegerField()
    is_sell = models.BooleanField(default=False)
    total = models.DecimalField(decimal_places=2,max_digits=10)
    updated = models.DateTimeField()
    
    def __str__(self):
        return f'{self.user.username} -> {self.stock_symbol} -> {self.updated.ctime()}'

    class Meta:
        ordering = ['-updated']

class History(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE, related_name='historys')
    stock_name = models.CharField(max_length=100)
    stock_symbol = models.CharField(max_length=31)
    stock_price = models.DecimalField(decimal_places=2, max_digits=10)
    shares = models.PositiveIntegerField()
    is_sell = models.BooleanField(default=False)
    time = models.DateTimeField()

    class Meta:
        ordering = ['-time']

    def __str__(self):
        return f'{self.user.username} -> {self.shares}'

class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE, primary_key=True)
    account_size = models.DecimalField(decimal_places=2, max_digits=10)
    account_balance = models.DecimalField(decimal_places=2, max_digits=10)
    def __str__(self):
        return f'{self.user.username} -> ${self.account_balance}'

dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
import yfinance as yf
from django.db import transaction
from .models import Stock, Transaction, UserProfile, History, BoughtStockTrack
from django.contrib.auth.models import User
import datetime
import requests
from django.utils import timezone
# Create your views here.


@login_required(redirect_field_name="next", login_url="accounts:login")
def portfolio(request):
    user = request.user
    user = User.objects.get(username=user.username)
    transactions = user.transactions.all()
    return render(request, 'dashboard/dashboard.html', context={
        'total': user.userprofile.account_size,
        'balance': user.userprofile.account_balance,
        'transactions':transactions
    })

@transaction.atomic
@login_required(redirect_field_name="next", login_url="accounts:login")
def buy(request):
    if request.method == 'POST':
        symbol = request.POST['symbol']
        shares = request.POST['shares']
        if len(symbol) > 0:
            symbol = symbol.strip().upper()
            try:
                test_it = requests.get(
                    'https://finance.cs50.net/static/favicon.ico', timeout=5.000)
            except:
                messages.error(request, 'No internet connection')
                return render(request, 'dashboard/buy.html')

            user = User.objects.get(username=request.user.username)
            try:
                a_stock = yf.Ticker(symbol)
                stock_info = a_stock.info
                # update this
                stocks = Stock.objects.filter(symbol=symbol)
                # if the stock model exists, we update the price to the currentPrice
                if stocks.exists():
                    stocks[0].price = stock_info['currentPrice']
                    # update this
                    stocks[0].updated = datetime.datetime.now()
                    stocks[0].save();
                    stock = stocks[0]
                    user.bought_stocks.add(stock)
                else:
                    stock = Stock()
                    stock.name = stock_info['shortName']
                    stock.symbol = stock_info['symbol']
                    stock.price = stock_info['currentPrice']
                    stock.website = stock_info['website']
                    stock.sector = stock_info['sector']
                    stock.industry = stock_info['industry']
                    stock.country = stock_info['country']
                    stock.logo_url = stock_info['logo_url']
                    stock.updated = datetime.datetime.now()
                    stock.save();
                    stock.users.add(user)
                total= stock.price * int(shares)
                user_transactions = user.transactions.all()
                one_transaction = [x for x in user_transactions if not x.is_sell and x.stock_symbol == stock.symbol]

                # store history
                history = History(user=user, stock_name=stock.name, stock_symbol=stock.symbol,
                                    stock_price=stock.price,shares=shares, time=datetime.datetime.now())

                # check if a transaction with the same name and type exists
                if len(one_transaction) == 1:                                 # get list of user bought stocks
                    bought_stocks_track = user.bought_stock_tracks.all()
                    if len(bought_stocks_track) >= 1:
                        stock_track = [x for x in bought_stocks_track if x.symbol == stock.symbol][0]
                    one = one_transaction[0]
                    one.updated = datetime.datetime.now()
                    one.shares += int(shares)
                    one.total += total
                    stock_track.shares += int(shares)
                else:
                    one = Transaction(user=user, stock_name=stock.name, stock_symbol=stock.symbol,
                                    stock_price=stock.price, total=total, shares=shares, updated=datetime.datetime.now())
                    stock_track = BoughtStockTrack(user=user,symbol=stock.symbol,shares=shares)
                balance = user.userprofile.account_balance
                if balance < total:
                    messages.error(request,f'Insufficient Cash, you only have ${balance}')
                    return redirect('dashboard:buy')
                balance = balance - int(total)
                userprofile = UserProfile.objects.get(user=user)
                userprofile.account_balance = balance
                # save to db
                stock_track.save();
                userprofile.save();
                one.save();   
                history.save();
                transactions = user.transactions.all()    
                messages.success(request,f'Your Purchase of {one.stock_symbol} was successful')     
                return render(request, 'dashboard/dashboard.html', context={
                    'transactions': transactions,
                    'total':user.userprofile.account_size,
                    'balance':balance
                })
            except:
                messages.error(request,'Invalid inputs')
                redirect('dashboard:buy')
        else:
            messages.error(request, 'Symbol cannot be empty')
    return render(request, 'dashboard/buy.html')


@login_required(redirect_field_name="next", login_url="accounts:login")
def sell(request):
    name = request.user.username
    user = User.objects.get(username=name)
    if request.method == 'POST':
        symbol = request.POST['symbol']
        shares = request.POST['shares']
        if len(symbol) > 0:
            symbol = symbol.strip().upper()
            try:
                test_it = requests.get(
                    'https://finance.cs50.net/static/favicon.ico', timeout=5.000)
            except:
                messages.error(request, 'No internet connection')
                return redirect('dashboard:sell')
            bought_stocks = user.bought_stocks.all()
            sell_stock = [x for x in bought_stocks if x.symbol == symbol]
            if len(sell_stock) < 1 :
                messages.error(request,f"you don't have {symbol}")
                return redirect('dashboard:sell')
            stock = sell_stock[0]
            try:
                a_stock = yf.Ticker(stock.symbol)
                stock_info = a_stock.info
                stock.price = stock_info['currentPrice']
                updated = datetime.datetime.now()
                stock.updated = updated
                stock.save();
                # get the stock tracker list
                bought_stocks_track = user.bought_stock_tracks.all()
                stock_track = [x for x in bought_stocks_track if x.symbol == stock.symbol][0]
                shares = int(shares)
                if stock_track.shares >= shares:
                    total = int(stock.price * shares)
                    # instantiate a transaction and history
                    history = History(user=user, stock_name=stock.name, stock_symbol=stock.symbol,
                                    stock_price=stock.price,shares=shares, time=updated, is_sell=True)

                    # check if a transaction with the same name and type(as in buy/sell ) exists
                    user_transactions = user.transactions.all()
                    one_transaction = [x for x in user_transactions if x.is_sell and x.stock_symbol == stock.symbol]
                    if len(one_transaction) == 1:
                        one = one_transaction[0]
                        one.updated = updated
                        one.shares += shares
                        one.total += total
                    else:
                        one = Transaction(user=user, stock_name=stock.name, stock_symbol=stock.symbol,
                                        stock_price=stock.price, total=total, shares=shares, updated=updated, is_sell=True)
                    stock_track.shares -= shares
                    balance = user.userprofile.account_balance
                    balance += total
                    user.userprofile.account_balance = balance
                    # save
                    stock_track.save();
                    user.userprofile.save();
                    one.save();
                    history.save();
                    transactions = user.transactions.all()  
                    messages.success(request,f'Sale of {stock.symbol} was successful !!') 
                    return render(request, 'dashboard/dashboard.html', context={
                    'transactions': transactions,
                    'total':user.userprofile.account_size,
                    'balance':balance
                    })
                else:
                    messages.error(request,f'{shares} >  amount of {stock.symbol} You have Ole')
                    return redirect('dashboard:sell')
            except:
                bought_stocks = user.bought_stock_tracks.all()
                bought_stocks = [x for x in bought_stocks if not x.shares == 0]
                messages.error(request,'Invalid Inputs')
                return render(request, 'dashboard/sell.html',context={
                    'stocks':bought_stocks,
                })
    else:
        bought_stocks = user.bought_stock_tracks.all()
        bought_stocks = [x for x in bought_stocks if not x.shares == 0]
        return render(request, 'dashboard/sell.html',context={
            'stocks':bought_stocks,
        })


@login_required(redirect_field_name="next", login_url="accounts:login")
def history(request):
    user = request.user
    user = User.objects.get(username=user.username)
    transactions = user.historys.all()
    num = len(transactions)
    if request.method == "POST":
        choice = request.POST['choice']
        if choice == 'yes':
            user.historys.all().delete()

templates/dashboard/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block title %}
    <title>Home</title>
    {% endblock %}
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@400;500;600;700&display=swap"
      rel="stylesheet"
    />

    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="https://finance.cs50.net/static/favicon.ico"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
      integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    {% block style %}
      {% endblock %}
  </head>
  <body>

    <header class="">
      <a href="{% url 'dashboard:index' %}" id="logo">
        <div class="logo">
          <h1>C</h1>
          <h1 id="dollar">$</h1>
          <h1>5</h1>
          <h1>0</h1>
          <p class="">Finance</p>
        </div>
      </a>
      <div class="desktop desktop-nav dashboard">
        <div class="a-links">
            <a href="{% url 'dashboard:quotes' %}">Quotes</a>
            <a href="{% url 'dashboard:buy' %}">Buy</a>
            <a href="{% url 'dashboard:sell' %}">Sell</a>
            <a href="{% url 'dashboard:history' %}">History</a>
        </div>
        <div class="div-btn">
            <a href="{% url 'accounts:logout' %}"><button>Logout</button></a>
        </div>
      </div>
      <div class="mobile mobile-nav">
        <i class="fa-solid fa-bars icon"></i>
      </div>
    </header>
    <main class="">
      <div class="mobile-drop-down mobile m-dashboard">
        <a href="{% url 'dashboard:quotes' %}">Quotes</a>
        <a href="{% url 'dashboard:buy' %}">Buy</a>
        <a href="{% url 'dashboard:sell' %}">Sell</a>
        <a href="{% url 'dashboard:history' %}">History</a>
        <a href="{% url 'accounts:logout' %}"><button>Logout</button></a>
      </div>
      {% block main %}
      {% endblock %}
    </main>
    <footer class="">
      <p>Data Provided by <a href="https://finance.yahoo.com/">yahoo finance</a></p>
    </footer>
    <script src="{% static 'script.js' %}"></script>
    {% block scripts %}
    {% endblock %}
  </body>
  <p class="spinner"><i class="fa-solid fa-spinner fa-5x" id="spinner"></i></p>
</html>

templates/dashboard/buy.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% block title %}
    <title>Buy</title>
{% endblock %}

{% block main %}

    {% if messages %}
        {% for message in messages %}
        <div class="ptag">
            <p class="{{ message.tags }} show django-message message-bg">{{ message }}</p>
        </div>
        {% endfor %}
        {% else %}
        <div class="ptag">
            <p class="show django-message message-bg">Buy a Stock Now!</p>
        </div>
    {% endif %}
    <form novalidate action="{% url 'dashboard:buy' %}" method="POST">
        {% csrf_token %}
        <div style="display: none;" class="stock-div">
            <img src="" alt="" id="stockimage">
        </div>
      <input type="text" placeholder="Symbol e.g TSL" id="symbol" name="symbol" />
      <p class="error-symbol error">Symbol cannot be empty</p>
      <input type="number" placeholder="Shares" id="shares" name="shares" min="1">
      <p class="error-shares error">Shares cannot be empty</p>
      <button type="submit">Buy</button>
    </form>
{% endblock %}

{% block scripts %}
    <script src="{% static 'dashboard/buy.js' %}"></script>
{% endblock %}

templates/dashboard/dashboard.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% block title %}
    <title>Portfolio</title>
{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'dashboard/portfolio.css' %}">
{% endblock %}

{% block main %}

    {% if messages %}
        {% for message in messages %}
        <div class="ptag">
            <p class="{{ message.tags }} show django-message message-bg">{{ message }}</p>
        </div>
        {% endfor %}
    {% endif %}
    <div class="table">
        <table class="">
            <div class="">
                <tr>
                    <th>Symbol</th>
                    <th>Name</th>
                    <th>Type</th>
                    <th>Shares</th>
                    <th>Price</th>
                    <th>Total</th>
                </tr>
            </div>
            <tbody>
                {% if transactions %}
                    {% for transaction in transactions %}
                        <div class="">
                            <tr>
                            <td class="">{{ transaction.stock_symbol }}</td>
                            <td class="">{{ transaction.stock_name }}</td>
                            {% if transaction.is_sell %}
                                <td style="color: rgb(9, 112, 9); font-weight:600;">Sell</td>
                            {% else %}
                                <td style="color: #1896df; font-weight:600;">Buy</td>
                            {% endif %}
                            <td class="">{{ transaction.shares }}</td>
                            <td class="">${{ transaction.stock_price }}</td>
                            <td class="">${{ transaction.total }}</td>
                            </tr>
                        </div>
                    {% endfor %}
                {% else %}
                {% endif %}
                <tr class="collate">
                  <td class=""></td>
                  <td class=""></td>
                  <td class=""></td>
                  <td class=""></td>
                  <td class="other">CASH</td>
                  <td class="">${{ balance }}</td>
                </tr>
                <tr class="collate">
                  <td class=""></td>
                  <td class=""></td>
                  <td class=""></td>
                  <td class=""></td>
                  <td class="other">TOTAL</td>
                  <td class="">${{ total }}</td>
                </tr>
            </tbody>
        </table>
    </div>
{% endblock %}

templates/dashboard/history.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% block title %}
    <title>History</title>
{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'dashboard/history.css' %}">
{% endblock %}

{% block main %}

    {% if messages %}
        {% for message in messages %}
        <div class="ptag">
            <p class="{{ message.tags }} show django-message message-bg">{{ message }}</p>
        </div>
        {% endfor %}
    {% endif %}
    <div class="table">
        <table class="">
            <div class="">
                <tr>
                    <th>Symbols</th>
                    <th>Type</th>
                    <th>Shares</th>
                    <th>Price</th>
                    <th>Transacted</th>
                </tr>
            </div>
            <tbody>
                {% if transactions %}
                {% for transaction in transactions %}
                    <div class="">
                        <tr class="">
                        <td class="">{{ transaction.stock_symbol }}</td>
                        {% if transaction.is_sell %}
                            <td style="color: rgb(9, 112, 9); font-weight:600;">Sell</td>
                        {% else %}
                            <td style="color: #1896df; font-weight:600;">Buy</td>
                        {% endif %}
                        <td class="">{{ transaction.shares }}</td>
                        <td class="">${{ transaction.stock_price }}</td>
                        <td class="">{{ transaction.time }}</td>
                        </tr>
                    </div>
                {% endfor %}
                {% else %}
                {% endif %}
              </tbody>
        </table>
    </div>
    {% if num >= 1 %}
    <form class="" method="POST" action="{% url 'dashboard:history' %}">
        {% csrf_token %}
        <input type="hidden" id="choice" name="choice" value="no">
        <button style="margin-top: 0;">Clear History</button>
    </form>
    <div class="after">
        <div class="nothing bdr" onclick="removeChoice()"></div>
        <div class="choice">
            <p>Do your really want to clear all?</p>
            <p class="button"><button value="yes" id="yes">Yes</button> <button value="no" id="no">No</button></p>
        </div>
    </div>
    {% endif %}
{% endblock %}
{% block scripts %}
    <script src="{% static 'dashboard/history.js' %}"></script>
{% endblock %}

templates/dashboard/quote.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% block title %}
    <title>Quotes</title>
{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'dashboard/quote.css' %}">
{% endblock %}

{% block main %}

    {% if messages %}
        {% for message in messages %} 
        <div class="ptag">
            <p class="{{ message.tags }} show django-message message-bg">{{ message }}</p>
        </div>
        {% endfor %}
        {% else %}
        <div class="ptag">
            <p class="show django-message message-bg">Check Out a Stock Now!</p>
        </div>
    {% endif %}

    <form novalidate action="{% url 'dashboard:quotes' %}" method="POST">
        {% csrf_token %}
      <input type="text" placeholder="Symbol e.g TSLA,AAPL" id="symbol" name="symbol" />
      <p class="error-symbol error">Symbol cannot be empty</p>
      <button type="submit">Quote</button>
    </form>

    <div class="quoted">
        {% if stock_exists %}
            <div class="row">
                <img src="{{ stock.logo_url }}" alt="" class="">
            </div>
            <h3>Name: {{ stock.name }}</h3>
            <h5>Symbol: {{ stock.symbol }}</h5>
            <h5>Current Price: ${{ stock.price }}</h5>
            <h5>Sector: {{ stock.sector }}</h5>
            <h5>Industry: {{ stock.industry }}</h5>
            <h5>Country: {{ stock.country }}</h5>
            <h5>Website: <a href="{{ stock.website }}">{{ stock.website }}</a></h5>
            <a href="{% url 'dashboard:buy' %}" class=""><button data-stock="{{ stock.symbol }}" onclick="storeName()">Buy {{ stock.symbol }}</button></a>
        {% else %}
            <h5>No Quotes Yet</h5>
        {% endif %}
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'dashboard/quote.js' %}"></script>
{% endblock %}

templates/dashboard/sell.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% block title %}
    <title>Sell</title>
{% endblock %}

{% block main %}

    {% if messages %}
        {% for message in messages %}
        <div class="ptag">
            <p class="{{ message.tags }} show django-message message-bg">{{ message }}</p>
        </div>
        {% endfor %}
        {% else %}
        <div class="ptag">
            <p class="show django-message message-bg">Sell a Stock Now!</p>
        </div>
    {% endif %}

    <form novalidate action="{% url 'dashboard:sell' %}" method="POST">
        {% csrf_token %}
        <div class="mainselection">
            <select name="symbol" id="symbol" class="">
                <option value="" class="">Select a Stock</option>
                {% if stocks %}
                {% for stock in stocks %}
                    <option value="{{ stock.symbol }}" class="">{{ stock.symbol }}</option>
                {% endfor %}
                {% endif %}                          
            </select>
        </div>
      <p class="error-symbol error">Symbol cannot be empty</p>
      <input type="number" placeholder="Shares" id="shares" name="shares" min="1">
      <p class="error-shares error">Shares cannot be empty</p>
      <button type="submit">Sell</button>
    </form>
    
{% endblock %}

{% block scripts %}
    <script src="{% static 'dashboard/sell.js' %}"></script>
{% endblock %}

templates/dashboard/test.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>test</title>
    <link rel="stylesheet" href="../../static/style.css" />
    <link rel="stylesheet" href="../../static/dashboard/portfolio.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@400;500;600;700&display=swap"
      rel="stylesheet"
    />

    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="https://finance.cs50.net/static/favicon.ico"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
      integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    
  </head>
  <body>
    <header class="">
      <a href="#" id="logo">
        <div class="logo">
          <h1>C</h1>
          <h1 id="dollar">$</h1>
          <h1>5</h1>
          <h1>0</h1>
          <p class="">Finance</p>
        </div>
      </a>
      <div class="desktop desktop-nav dashboard">
        <div class="a-links">
            <a href="#">Quotes</a>
            <a href="#">Buy</a>
            <a href="#">Sell</a>
            <a href="#">History</a>
        </div>
        <div class="div-btn">
            <a href="#"><button>Logout</button></a>
        </div>
      </div>
      <div class="mobile mobile-nav">
        <i class="fa-solid fa-bars icon"></i>
      </div>
    </header>
    <main class="">
      <div class="mobile-drop-down mobile m-dashboard">
        <a href="#">Quotes</a>
        <a href="#">Buy</a>
        <a href="#">Sell</a>
        <a href="#">History</a>
        <a href="#}"><button>Logout</button></a>
      </div>

      <div class="ptag">
        <p class="show django-message message-bg">messages choke o</p>
        </div>

      <div class="table">
        <table class="">
            <div class="">
                <tr>
                    <th>Symbol</th>
                    <th>Name</th>
                    <th>Type</th>
                    <th>Shares</th>
                    <th>Price</th>
                    <th>Total</th>
                </tr>
            </div>
            <tbody>
                        <div class="">
                            <tr>
                            <td class="">MSFT</td>
                            <td class="">Microsoft Incorporation 1999</td>
        
                                <td style="color: #1896df; font-weight:600;">Buy</td>
                            <td class="">10</td>
                            <td class="">$10</td>
                            <td class="">$256</td>
                            </tr>
                        </div>
                <tr class="collate">
                  <td class=""></td>
                  <td class=""></td>
                  <td class=""></td>
                  <td class=""></td>
                  <td class="other">CASH</td>
                  <td class="">$8780</td>
                </tr>
                <tr class="collate">
                  <td class=""></td>
                  <td class=""></td>
                  <td class=""></td>
                  <td class=""></td>
                  <td class="other">TOTAL</td>
                  <td class="">$10000</td>
                </tr>
            </tbody>
        </table>
    </div>
    <form class="">
        <input type="hidden" name="choice" value="no">
        <button style="margin-top: 0;">Clear History</button>
    </form>
    <div class="after hide">
        <div class="choice">
            <p>Do your really want to clear all?</p>
            <p class="button"><button style="color: red;" value="yes" id="yes">Yes</button> <button style="color: blue;" value="no" id="no">No</button></p>
        </div>
    </div>
    </main>
    <footer class="">
      <p>Data Provided by <a href="https://finance.yahoo.com/">yahoo finance</a></p>
    </footer>
    <script src="../../static/script.js"></script>
    <script src="../../static/dashboard/history.js"></script>
    
  </body>
  <p class="spinner"><i class="fa-solid fa-spinner fa-5x" id="spinner"></i></p>
</html>